[project]
name = "HyPE-Experiments"
authors = [{name = "John Zeng", email = "zeng261@purdue.edu"}]
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/JLZ22/HyPE-Experiments"